name: Auto-close Issues not adhering to templates

on:
  issues:
    types: [opened, edited]

jobs:
  auto_close_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Automatically close issues that don't follow the issue template
        uses: marcelklehr/auto-close-issues@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-close-message: "Hi @${issue.user.login}! This issue is being automatically closed because it does not follow the issue template." # optional property
          closed-issues-label: "🙁 Not following issue template" # optional property
